"""Contains code for fetching different transforms policies."""


def get_transforms(key: str):
    """Return a set of transforms based on policy key.

    Possible values for key are:
    'imagenet': policy from torchvision's autoaugment [1]
    'cifar10: policy from torchvision's autoaugment [1]
    'svhn' policy from torchvision's autoaugment [1]
    'policy_v0': policy from tensorflow's tpu autoaugment [2]

    Sources:
        [1] https://pytorch.org/vision/master/_modules/torchvision/transforms/autoaugment.html  # noqa: E501
        [2] https://github.com/tensorflow/tpu/blob/0b33da3bdfc3706666dfa25631e0eed76a111e07/models/official/efficientnet/autoaugment.py#L36  # noqa: E501
    """
    all_policies = {
        "imagenet": [
            (("Posterize", 0.4, 8), ("Rotate", 0.6, 9)),
            (("Solarize", 0.6, 5), ("AutoContrast", 0.6, None)),
            (("Equalize", 0.8, None), ("Equalize", 0.6, None)),
            (("Posterize", 0.6, 7), ("Posterize", 0.6, 6)),
            (("Equalize", 0.4, None), ("Solarize", 0.2, 4)),
            (("Equalize", 0.4, None), ("Rotate", 0.8, 8)),
            (("Solarize", 0.6, 3), ("Equalize", 0.6, None)),
            (("Posterize", 0.8, 5), ("Equalize", 1.0, None)),
            (("Rotate", 0.2, 3), ("Solarize", 0.6, 8)),
            (("Equalize", 0.6, None), ("Posterize", 0.4, 6)),
            (("Rotate", 0.8, 8), ("Color", 0.4, 0)),
            (("Rotate", 0.4, 9), ("Equalize", 0.6, None)),
            (("Equalize", 0.0, None), ("Equalize", 0.8, None)),
            (("Invert", 0.6, None), ("Equalize", 1.0, None)),
            (("Color", 0.6, 4), ("Contrast", 1.0, 8)),
            (("Rotate", 0.8, 8), ("Color", 1.0, 2)),
            (("Color", 0.8, 8), ("Solarize", 0.8, 7)),
            (("Sharpness", 0.4, 7), ("Invert", 0.6, None)),
            (("ShearX", 0.6, 5), ("Equalize", 1.0, None)),
            (("Color", 0.4, 0), ("Equalize", 0.6, None)),
            (("Equalize", 0.4, None), ("Solarize", 0.2, 4)),
            (("Solarize", 0.6, 5), ("AutoContrast", 0.6, None)),
            (("Invert", 0.6, None), ("Equalize", 1.0, None)),
            (("Color", 0.6, 4), ("Contrast", 1.0, 8)),
            (("Equalize", 0.8, None), ("Equalize", 0.6, None)),
        ],
        "cifar10": [
            (("Invert", 0.1, None), ("Contrast", 0.2, 6)),
            (("Rotate", 0.7, 2), ("TranslateX", 0.3, 9)),
            (("Sharpness", 0.8, 1), ("Sharpness", 0.9, 3)),
            (("ShearY", 0.5, 8), ("TranslateY", 0.7, 9)),
            (("AutoContrast", 0.5, None), ("Equalize", 0.9, None)),
            (("ShearY", 0.2, 7), ("Posterize", 0.3, 7)),
            (("Color", 0.4, 3), ("Brightness", 0.6, 7)),
            (("Sharpness", 0.3, 9), ("Brightness", 0.7, 9)),
            (("Equalize", 0.6, None), ("Equalize", 0.5, None)),
            (("Contrast", 0.6, 7), ("Sharpness", 0.6, 5)),
            (("Color", 0.7, 7), ("TranslateX", 0.5, 8)),
            (("Equalize", 0.3, None), ("AutoContrast", 0.4, None)),
            (("TranslateY", 0.4, 3), ("Sharpness", 0.2, 6)),
            (("Brightness", 0.9, 6), ("Color", 0.2, 8)),
            (("Solarize", 0.5, 2), ("Invert", 0.0, None)),
            (("Equalize", 0.2, None), ("AutoContrast", 0.6, None)),
            (("Equalize", 0.2, None), ("Equalize", 0.6, None)),
            (("Color", 0.9, 9), ("Equalize", 0.6, None)),
            (("AutoContrast", 0.8, None), ("Solarize", 0.2, 8)),
            (("Brightness", 0.1, 3), ("Color", 0.7, 0)),
            (("Solarize", 0.4, 5), ("AutoContrast", 0.9, None)),
            (("TranslateY", 0.9, 9), ("TranslateY", 0.7, 9)),
            (("AutoContrast", 0.9, None), ("Solarize", 0.8, 3)),
            (("Equalize", 0.8, None), ("Invert", 0.1, None)),
            (("TranslateY", 0.7, 9), ("AutoContrast", 0.9, None)),
        ],
        "svhn": [
            (("ShearX", 0.9, 4), ("Invert", 0.2, None)),
            (("ShearY", 0.9, 8), ("Invert", 0.7, None)),
            (("Equalize", 0.6, None), ("Solarize", 0.6, 6)),
            (("Invert", 0.9, None), ("Equalize", 0.6, None)),
            (("Equalize", 0.6, None), ("Rotate", 0.9, 3)),
            (("ShearX", 0.9, 4), ("AutoContrast", 0.8, None)),
            (("ShearY", 0.9, 8), ("Invert", 0.4, None)),
            (("ShearY", 0.9, 5), ("Solarize", 0.2, 6)),
            (("Invert", 0.9, None), ("AutoContrast", 0.8, None)),
            (("Equalize", 0.6, None), ("Rotate", 0.9, 3)),
            (("ShearX", 0.9, 4), ("Solarize", 0.3, 3)),
            (("ShearY", 0.8, 8), ("Invert", 0.7, None)),
            (("Equalize", 0.9, None), ("TranslateY", 0.6, 6)),
            (("Invert", 0.9, None), ("Equalize", 0.6, None)),
            (("Contrast", 0.3, 3), ("Rotate", 0.8, 4)),
            (("Invert", 0.8, None), ("TranslateY", 0.0, 2)),
            (("ShearY", 0.7, 6), ("Solarize", 0.4, 8)),
            (("Invert", 0.6, None), ("Rotate", 0.8, 4)),
            (("ShearY", 0.3, 7), ("TranslateX", 0.9, 3)),
            (("ShearX", 0.1, 6), ("Invert", 0.6, None)),
            (("Solarize", 0.7, 2), ("TranslateY", 0.6, 7)),
            (("ShearY", 0.8, 4), ("Invert", 0.8, None)),
            (("ShearX", 0.7, 9), ("TranslateY", 0.8, 3)),
            (("ShearY", 0.8, 5), ("AutoContrast", 0.7, None)),
            (("ShearX", 0.7, 2), ("Invert", 0.1, None)),
        ],
        "policy_v0": [
            (("Equalize", 0.8, 1), ("ShearY", 0.8, 4)),
            (("Color", 0.4, 9), ("Equalize", 0.6, 3)),
            (("Color", 0.4, 1), ("Rotate", 0.6, 8)),
            (("Solarize", 0.8, 3), ("Equalize", 0.4, 7)),
            (("Solarize", 0.4, 2), ("Solarize", 0.6, 2)),
            (("Color", 0.2, 0), ("Equalize", 0.8, 8)),
            (("Equalize", 0.4, 8), ("SolarizeAdd", 0.8, 3)),
            (("ShearX", 0.2, 9), ("Rotate", 0.6, 8)),
            (("Color", 0.6, 1), ("Equalize", 1.0, 2)),
            (("Invert", 0.4, 9), ("Rotate", 0.6, 0)),
            (("Equalize", 1.0, 9), ("ShearY", 0.6, 3)),
            (("Color", 0.4, 7), ("Equalize", 0.6, 0)),
            (("Posterize", 0.4, 6), ("AutoContrast", 0.4, 7)),
            (("Solarize", 0.6, 8), ("Color", 0.6, 9)),
            (("Solarize", 0.2, 4), ("Rotate", 0.8, 9)),
            (("Rotate", 1.0, 7), ("TranslateY", 0.8, 9)),
            (("ShearX", 0.0, 0), ("Solarize", 0.8, 4)),
            (("ShearY", 0.8, 0), ("Color", 0.6, 4)),
            (("Color", 1.0, 0), ("Rotate", 0.6, 2)),
            (("Equalize", 0.8, 4), ("Equalize", 0.0, 8)),
            (("Equalize", 1.0, 4), ("AutoContrast", 0.6, 2)),
            (("ShearY", 0.4, 7), ("SolarizeAdd", 0.6, 7)),
            (("Posterize", 0.8, 2), ("Solarize", 0.6, 10)),
            (("Solarize", 0.6, 8), ("Equalize", 0.6, 1)),
            (("Color", 0.8, 6), ("Rotate", 0.4, 5)),
        ],
    }
    return all_policies[key]
