name: CI

on:
  pull_request:
    branches: [ main ]

jobs:
  CI:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ 3.6, 3.7, 3.8 ]
        tensorflow-version: [ 2.4.1 ]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies (TF version ${{ matrix.tensorflow-version }})
        run: |
          python -m pip install --upgrade pip
          python -m pip install tensorflow-cpu==${{matrix.tensorflow-version}}
          pip install -r requirements.txt
          pip install -r tf_autoaugment/tests/requirements.txt
          pip install -e .

      - name: Lint job
        run: make lint

      - name: Run tests
        run: make test
